"""
Django settings for python_if_this_then_that project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

API_KEY = 'OBABY_MARS'
API_SECRCT = 'H4CKORGCN'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^%!s1pu0$uw6sux#8e^t6kq^=e2b$*5uj*g*(47*01c3+0x@(i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ifdata',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'python_if_this_then_that.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'python_if_this_then_that.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


import time

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'menu_display': ['权限认证', 'IF数据', '相关链接'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'ifdata',
        'name': 'IF数据',
        'icon': 'fa fa-life-ring',
        'models': [
            {
                'name': 'IF Type(类型)',
                'icon': 'fa fa-users',
                'url': '/admin/ifdata/ifttttype/'
            },
            {
                'name': 'IF This(条件)',
                'icon': 'fa fa-tasks',
                'url': '/admin/ifdata/ifthis/'
            },
            {
                'name': 'Action(动作)',
                'icon': 'fa fa-bell',
                'url': '/admin/ifdata/thataction/'
            },
        ]
    }, {
        'app': 'auth',
        'name': '权限认证',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': '/admin/auth/user/'
        },
            {
                'name': '用户组',
                'icon': 'fa fa-users',
                'url': '/admin/auth/group/'
            },
            {
                'name': '认证令牌',
                'icon': 'fa fa-users',
                'url': '/admin/authtoken/token/'
            }
        ]
    }, {
        'name': '相关链接',
        'icon': 'fa fa-desktop',
        'models': [
            {
                'name': 'obaby@mars',  # time.time(),
                'url': 'http://www.obaby.org.cn',
                'icon': 'far fa-heart'
            }
        ,{
                'name': 'Pif3t',  # time.time(),
                'url': '/',
                'icon': 'far fa-eye'
            }
        ]
    }]
}
