# Generated by Django 3.1 on 2020-08-18 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFTTTType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=64, null=True)),
                ('describe', models.TextField(blank=True, help_text='说明', max_length=4095, null=True)),
                ('type_id', models.IntegerField(default=1, help_text='类型ID')),
            ],
            options={
                'verbose_name': 'IFTTT类型',
                'verbose_name_plural': 'IFTTT类型',
            },
        ),
        migrations.CreateModel(
            name='ThatAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('action_type', models.IntegerField(default=0, help_text='动作类型')),
                ('http_url', models.CharField(blank=True, help_text='Http请求URL', max_length=1024, null=True)),
                ('http_header', models.CharField(blank=True, help_text='Http请求Header', max_length=1024, null=True)),
                ('http_body', models.CharField(blank=True, help_text='Http请求Body', max_length=1024, null=True)),
                ('http_method', models.CharField(default='get', help_text='Http请求方法', max_length=8)),
                ('name', models.CharField(blank=True, help_text='名称', max_length=64, null=True)),
                ('describe', models.TextField(blank=True, help_text='说明', max_length=4095, null=True)),
            ],
            options={
                'verbose_name': 'ThatAction',
                'verbose_name_plural': 'ThatAction',
            },
        ),
        migrations.CreateModel(
            name='IfThis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('update', models.DateTimeField(auto_now=True, help_text='修改时间')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=64, null=True)),
                ('describe', models.TextField(blank=True, help_text='说明', max_length=4095, null=True)),
                ('condition_type', models.CharField(default='has', help_text='关键词匹配方法', max_length=16)),
                ('key_words', models.CharField(blank=True, help_text='关键词列表 | 分割', max_length=128, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='父条件', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifdata.ifthis')),
                ('that_action', models.ForeignKey(blank=True, help_text='动作行为', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifdata.thataction')),
            ],
            options={
                'verbose_name': 'ThatAction',
                'verbose_name_plural': 'ThatAction',
            },
        ),
    ]
