# Generated by Django 3.1 on 2020-08-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ifthis',
            options={'verbose_name': 'IfThis', 'verbose_name_plural': 'IfThis'},
        ),
        migrations.AddField(
            model_name='ifthis',
            name='enable',
            field=models.BooleanField(default=True, help_text='是否激活'),
        ),
    ]
