# Generated by Django 3.1 on 2020-08-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifdata', '0002_auto_20200818_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifthis',
            name='response_text',
            field=models.TextField(blank=True, help_text='反馈文本', null=True),
        ),
    ]
