# Generated by Django 3.1 on 2020-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifdata', '0004_auto_20200818_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifthis',
            name='no_action_response_text',
            field=models.TextField(blank=True, help_text='未绑定动作反馈文本 随机文本反馈根据换行分割', null=True),
        ),
        migrations.AlterField(
            model_name='thataction',
            name='response_text',
            field=models.TextField(blank=True, help_text='动作执行反馈文本 随机文本反馈根据换行分割', null=True),
        ),
    ]
