# Generated by Django 3.1 on 2020-08-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifdata', '0005_auto_20200818_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifthis',
            name='that_action',
        ),
        migrations.AddField(
            model_name='ifthis',
            name='that_action',
            field=models.ManyToManyField(blank=True, help_text='动作行为', null=True, to='ifdata.ThatAction'),
        ),
    ]
