# Generated by Django 3.1 on 2020-08-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifdata', '0007_auto_20200818_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifthis',
            name='priority',
            field=models.IntegerField(default=0, help_text='检索优先级'),
        ),
    ]
